

import Dashboard from './Dashboard';
import { Login,UpdateprofilClub, LoginSponsor,LoginStudent,AddEvent, LoginAdministrateur, ProfilSponsor, Page404, Page500,RegisterSponsor, RegisterStudent ,RegisterAdministration,Forgetpassword,Verification, ProfilAdministrateur, ProfilStudent, AddUniversity, AddEstablishment, ClubProfil, Acceuil, Club, Eventlist } from './Pages';


export {
  Badges,
  Club,
  AddEvent,
  Eventlist,
  Acceuil,
  ProfilAdministrateur,
  ProfilStudent,
  ClubProfil,
  LoginSponsor,
  LoginStudent,
  UpdateprofilClub,
  LoginAdministrateur,
  ProfilSponsor,
  Page404,
  AddUniversity,
  AddEstablishment,
  Forgetpassword,
  Verification,
  Page500,
  RegisterStudent,
  RegisterSponsor,
  RegisterAdministration,
  Login,
  Modals,
  Alerts,
  Flags,
  Card,
  Tooltips,
  Tabs,
  Tables,
  Dashboard,
  Jumbotrons,
  Switches,
  ProgressBar,
  Popovers,
  Navs,
  Navbars,
  ListGroups,
  Forms,
  Dropdowns,
  Collapses,
  Carousels,
  Breadcrumbs,
  Paginations,
};

