

import Dashboard from './Dashboard';
import { Login, Login1,Login2, Login3, ProfilSponsor, Page404, Page500,RegisterSponsor, RegisterStudent ,RegisterAdministration,Forgetpassword,Verification, ProfilAdministrateur, ProfilStudent, Updateprofil, AddUniversity, AddEstablishment, ClubProfil, Acceuil, Club, Eventlist } from './Pages';


export {
  Badges,
  Club,
  Eventlist,
  Acceuil,
  ProfilAdministrateur,
  ProfilStudent,
  ClubProfil,
  Login1,
  Login2,
  Login3,
  ProfilSponsor,
  Page404,
  AddUniversity,
  AddEstablishment,
  Updateprofil,
  Forgetpassword,
  Verification,
  Page500,
  RegisterStudent,
  RegisterSponsor,
  RegisterAdministration,
  Login,
  Modals,
  Alerts,
  Flags,
  Card,
  Tooltips,
  Tabs,
  Tables,
  Dashboard,
  Jumbotrons,
  Switches,
  ProgressBar,
  Popovers,
  Navs,
  Navbars,
  ListGroups,
  Forms,
  Dropdowns,
  Collapses,
  Carousels,
  Breadcrumbs,
  Paginations,
};

